# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - flux_retour_cfas_nginx_data:/data
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env

  ui:
    mem_limit: 1.5g
    stdin_open: true
    volumes:
      - ./ui:/app:z
      - /app/.next
      - /app/node_modules
    build:
      context: ui
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_ENV=dev
        - NEXT_PUBLIC_BASE_URL=http://localhost
        - NEXT_PUBLIC_BASE_HOST=localhost
        - NEXT_PUBLIC_METABASE_URL=https://localhost/metabase
        - NEXT_PUBLIC_METABASE_SECRET_KEY=
        - SKIP_PREFLIGHT_CHECK=true
    environment:
      - NEXT_PUBLIC_SENTRY_DSN=

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - /app/node_modules/@esbuild/ # exclus du mount et (re)-installer dans le Dockerfile pour avoir le bon driver
      - /app/node_modules/esbuild/ # exclus du mount et (re)-installer dans le Dockerfile pour avoir le bon driver
      - ./server:/app:z # Allows source folders to be watched
    environment:
      - FLUX_RETOUR_CFAS_ENV=dev
      - FLUX_RETOUR_CFAS_LOG_LEVEL=debug
      - FLUX_RETOUR_CFAS_LOG_DESTINATIONS=stdout,mongodb
      - FLUX_RETOUR_CFAS_SMTP_HOST=smtp
      - FLUX_RETOUR_CFAS_SMTP_PORT=1025
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_AUTH_API_TOKEN_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_SENTRY_DSN=
    depends_on:
      - smtp

  queue_processor:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/@esbuild/ # exclus du mount et (re)-installer dans le Dockerfile pour avoir le bon driver
      - /app/node_modules/esbuild/ # exclus du mount et (re)-installer dans le Dockerfile pour avoir le bon driver
      - ./server:/app:z # Allows source folders to be watched
    environment:
      - FLUX_RETOUR_CFAS_ENV=dev
      - FLUX_RETOUR_CFAS_LOG_LEVEL=debug
      - FLUX_RETOUR_CFAS_LOG_DESTINATIONS=stdout,mongodb
      - FLUX_RETOUR_CFAS_SMTP_HOST=smtp
      - FLUX_RETOUR_CFAS_SMTP_PORT=1025
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_AUTH_API_TOKEN_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET=secret
      - FLUX_RETOUR_CFAS_SENTRY_DSN=
    depends_on:
      - smtp

  mongodb:
    image: mongo:6.0.2-focal
    container_name: flux_retour_cfas_mongodb
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - flux_retour_cfas_network
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - flux_retour_cfas_mongodb_data:/data

  clamav:
    image: clamav/clamav
    ports:
      - 3310:3310

  smtp:
    image: axllent/mailpit:v1.5.5
    container_name: flux_retour_cfas_smtp
    restart: unless-stopped
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - flux_retour_cfas_network
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - flux_retour_cfas_smtp_data:/data
    depends_on:
      - mongodb

volumes:
  flux_retour_cfas_mongodb_data:
    driver: local
    name: flux_retour_cfas_mongodb_data
  flux_retour_cfas_nginx_data:
    driver: local
    name: flux_retour_cfas_nginx_data
  flux_retour_cfas_smtp_data:
    driver: local
    name: flux_retour_cfas_smtp_data
