- name: "Deploiement de la branche {{ git_revision }}"
  shell: "sudo /opt/flux-retour-cfas/start-app.sh {{ git_revision }}"
  register: output
- debug:
    var: output.stdout

- name: "Migrations de la base mongoDb"
  shell: "sudo /opt/flux-retour-cfas/run-migrations.sh"
  register: output
- debug:
    var: output.stdout

- name: "Cr√©ation des index de la base mongoDb"
  shell: "sudo /opt/flux-retour-cfas/run-indexes-creation.sh"
  register: output

- debug:
    var: output.stdout
