#Override containers for ovh environments
version: "2.4"
services:
  ui:
    build:
      args:
        - REACT_APP_ENV=dev

  server:
    environment:
      - FLUX_RETOUR_CFAS_ENV=dev
      - FLUX_RETOUR_CFAS_LOG_LEVEL=info
      - FLUX_RETOUR_CFAS_LOG_TYPE=json
      - FLUX_RETOUR_CFAS_PUBLIC_URL=https://cfas-dev.apprentissage.beta.gouv.fr
      - FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL={{ vault.FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_HASH_ROUNDS }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET_EXPIRES={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET_EXPIRES }}
      # MongoDb
      - FLUX_RETOUR_CFAS_MONGODB_URI={{ vault[env_type].FLUX_RETOUR_CFAS_MONGODB_URI }}
      # APIs
      - FLUX_RETOUR_CFAS_TABLES_CORRESPONDANCES_ENDPOINT_URL=https://tables-correspondances-recette.apprentissage.beta.gouv.fr/api
      - FLUX_RETOUR_CFAS_MNA_CATALOG_ENDPOINT_URL=https://catalogue-recette.apprentissage.beta.gouv.fr/api
      - FLUX_RETOUR_CFAS_LBA_ENDPOINT_URL=http://labonnealternance-recette.apprentissage.beta.gouv.fr/api
      # ADMIN
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS }}
      # OVH Storage
      - FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_AUTH_URL={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_AUTH_URL }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_REGION={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_REGION }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME }}
