#Override containers for ovh environments
version: "2.4"
services:
  reverse_proxy:
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem
    volumes:
      - /opt/flux-retour-cfas/data/nginx:/data
      - /opt/flux-retour-cfas/data/ssl:/ssl:ro
      - /opt/flux-retour-cfas/.overrides/reverse_proxy/includes:/etc/nginx/templates/includes/env

  server:
    environment:
      - FLUX_RETOUR_CFAS_CLAMAV_URI=clamav:3310

  metabase:
    image: metabase/metabase:v0.46.6.4
    mem_limit: 2g
    container_name: flux_retour_cfas_metabase
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_SITE_LOCALE: fr
      MB_SITE_URL: http://0.0.0.0/metabase
      MB_PASSWORD_COMPLEXITY: strong
      MB_START_OF_WEEK: monday
      MB_DB_TYPE: mysql
      MB_ENCRYPTION_SECRET_KEY: {{vault[env_type].FLUX_RETOUR_CFAS_METABASE_ENCRYPTION_SECRET_KEY}}
      MB_EMAIL_SMTP_HOST: {{vault[env_type].FLUX_RETOUR_CFAS_SMTP_HOST}}
      MB_EMAIL_SMTP_PORT: {{vault[env_type].FLUX_RETOUR_CFAS_SMTP_PORT}}
      MB_EMAIL_SMTP_USERNAME: {{vault[env_type].FLUX_RETOUR_CFAS_SMTP_AUTH_USER}}
      MB_EMAIL_SMTP_PASSWORD: {{vault[env_type].FLUX_RETOUR_CFAS_SMTP_AUTH_PASS}}
      MB_EMAIL_SMTP_SECURITY: tls
    restart: always
    networks:
      - flux_retour_cfas_network

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    restart: unless-stopped
    container_name: nodeexporter
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - flux_retour_cfas_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - flux_retour_cfas_network
