#Override containers for ovh environments
version: "2.4"
services:
  server:
    environment:
      - FLUX_RETOUR_CFAS_ENV=recette
      - FLUX_RETOUR_CFAS_LOG_LEVEL=debug
      - FLUX_RETOUR_CFAS_LOG_TYPE=json
      - FLUX_RETOUR_CFAS_PUBLIC_URL=https://cfas-recette.apprentissage.beta.gouv.fr
      - FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL={{ vault.FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET }}
      # MongoDb
      - FLUX_RETOUR_CFAS_MONGODB_URI={{ vault[env_type].FLUX_RETOUR_CFAS_MONGODB_URI }}
      # ADMIN
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS }}
      # OVH Storage
      - FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_URI={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_URI }}
      - FLUX_RETOUR_CFAS_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_KEY }}
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_SMTP_HOST={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_HOST }}
      - FLUX_RETOUR_CFAS_SMTP_PORT={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_PORT }}
      - FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY }}
      - FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY }}
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  queue_processor:
    environment:
      - FLUX_RETOUR_CFAS_ENV=recette
      - FLUX_RETOUR_CFAS_LOG_LEVEL=debug
      - FLUX_RETOUR_CFAS_LOG_TYPE=json
      - FLUX_RETOUR_CFAS_PUBLIC_URL=https://cfas-recette.apprentissage.beta.gouv.fr
      - FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL={{ vault.FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET }}
      # MongoDb
      - FLUX_RETOUR_CFAS_MONGODB_URI={{ vault[env_type].FLUX_RETOUR_CFAS_MONGODB_URI }}
      # ADMIN
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS }}
      # OVH Storage
      - FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_URI={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_URI }}
      - FLUX_RETOUR_CFAS_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_KEY }}
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_SMTP_HOST={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_HOST }}
      - FLUX_RETOUR_CFAS_SMTP_PORT={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_PORT }}
      - FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY }}
      - FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY }}
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  jobs_processor:
    environment:
      - FLUX_RETOUR_CFAS_ENV=recette
      - FLUX_RETOUR_CFAS_LOG_LEVEL=debug
      - FLUX_RETOUR_CFAS_LOG_TYPE=json
      - FLUX_RETOUR_CFAS_PUBLIC_URL=https://cfas-recette.apprentissage.beta.gouv.fr
      - FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL={{ vault.FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET }}
      # MongoDb
      - FLUX_RETOUR_CFAS_MONGODB_URI={{ vault[env_type].FLUX_RETOUR_CFAS_MONGODB_URI }}
      # ADMIN
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS }}
      # OVH Storage
      - FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_URI={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_URI }}
      - FLUX_RETOUR_CFAS_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_KEY }}
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_SMTP_HOST={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_HOST }}
      - FLUX_RETOUR_CFAS_SMTP_PORT={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_PORT }}
      - FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY }}
      - FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY }}
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  ui:
    build:
      args:
        - NEXT_PUBLIC_ENV=recette
        - NEXT_PUBLIC_BASE_URL=https://cfas-recette.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_BASE_HOST=cfas-recette.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_URL=https://cfas-recette.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_SECRET_KEY={{ vault[env_type].NEXT_PUBLIC_METABASE_SECRET_KEY }}
        - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  metabase:
    environment:
      MB_SITE_URL: https://cfas-recette.apprentissage.beta.gouv.fr/metabase
      MB_DB_CONNECTION_URI: {{vault[env_type].FLUX_RETOUR_CFAS_METABASE_DB_URI}}

  smtp:
    image: axllent/mailpit:v1.5.5
    container_name: flux_retour_cfas_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - flux_retour_cfas_network
    volumes:
      - /opt/flux-retour-cfas/repository/.infra/ansible/roles/setup/files/app/.overrides/recette/mailpit/auth:/auth
      - /opt/flux-retour-cfas/data/smtp:/data
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_UI_AUTH_FILE=/auth

  nodeexporter:
    hostname: tableau-de-bord-recette

  cadvisor:
    hostname: tableau-de-bord-recette
