name: Deployment subworkflow
on:
  workflow_call:
    inputs:
      environment:
        description: The environment to deploy to
        type: string
        required: true
      server_ip:
        description: The targeted server
        type: string
        required: true
      user:
        description: The server user to connect
        type: string
        required: true
    secrets:
      SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      SSH_KNOWN_HOSTS:
        description: SSH known hosts list
        required: true
      SLACK_WEBHOOK_URL:
        description: Slack webhook URL
        required: true
    outputs:
      status:
        description: Whether deployment succeeded or not
        value: ${{ jobs.deploy.outputs.status }}
jobs:
  deploy:
    name: Deploy on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github_actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host ${{inputs.server_ip}}
              HostName ${{inputs.server_ip}}
              User ${{inputs.user}}
              IdentityFile ~/.ssh/github_actions

      - name: Run playbook
        run: |
          bash .infra/scripts/deploy-app.sh ${{ inputs.environment }}

      - name: Notify failure on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Le déploiement en ${{ inputs.environment }} a échoué"
          notify_when: "failure"
          mention_groups: "!channel"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify success on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Déploiement en ${{ inputs.environment }} terminé avec succès"
          notify_when: "success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
