name: Deploy
on:
  push:
    branches: [master, recette]
  pull_request:
    branches: [master, recette]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - shell: bash
        run: echo 'FLUX_RETOUR_CFAS_HEAD_REF=${{ github.head_ref }}' >> $GITHUB_ENV

      - shell: bash
        run: echo 'FLUX_RETOUR_CFAS_HEAD_REF=${{ github.ref }}' >> $GITHUB_ENV

      - name: Check output
        run: echo ${FLUX_RETOUR_CFAS_HEAD_REF:-${FLUX_RETOUR_CFAS_HEAD_REF##*/}}

      - name: Request deployment recette
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/flux-retour-cfas-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "recette", "branchName":"recette"}'
        if: github.ref == 'refs/heads/recette'

      - name: Request deployment production
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/flux-retour-cfas-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "production", "branchName":"master"}'
        if: github.ref == 'refs/heads/master'
